### ISSUE TITLE
Update Issue Templates. 

### ISSUE THREAD

**Issue by droidbg** [droidbg/climator#1]
### Is there an existing issue for this?

- [ ] I have searched the [existing issues](https://github.com/droidbg/climator/issues)
- [ ] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Currently Issue Templates  present [here](https://github.com/droidbg/Climater/tree/master/.github/ISSUE_TEMPLATE) are demo templates, and are not compatible with this project.

### Proposal

Make changes in the template. 
Some Examples:  
```
Thank you for using Flutter!
to 
Thank you for using Climator!
```

```
I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)
   
to 

I have searched the [existing issues](https://github.com/droidbg/Climater/issues)
```

**Comment by Willmayyy** [comment]
can i be assigned

**Comment by droidbg** [comment]
ofcourse @Willmayyy, thanks for offering :)

**Comment by Willmayyy** [comment]
I updated all 11 of the issue templates. this was my pull request for hacktoberfest, if I did anything wrong please let me know.

**Comment by droidbg** [comment]
@Willmayyy Thanks for helping out.
