### ISSUE TITLE
Fix Code Analysis Issue

### ISSUE THREAD

**Issue by droidbg** [droidbg/climator#2]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/droidbg/climator/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Remove dart analysis errors and warning present in code. 

### Proposal

Currently there are many analysis issue present in code that can be removed 

Like : 
`Constructor declarations should be before non-constructor declarations.`
`Missing type annotation`

and so on..

**Comment by Teja-11** [comment]
can you assign this to me?

**Comment by droidbg** [comment]
@Teja-11 sure, thanks for offering
