### ISSUE TITLE
Refactor code 

### ISSUE THREAD

**Issue by droidbg** [droidbg/climator#5]
### Is there an existing issue for this?

- [ ] I have searched the [existing issues](https://github.com/droidbg/climator/issues)
- [ ] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Current code is written 2 years back, although dart 3 is migrated recently, but still many things needs to be refactored, and code needs best practices. 

### Proposal

Use Best Code practices in the code, like deducing code in different folders like dls, network, config. 
Or other practice like 
```
Variable naming conventions
Class and function naming conventions
Clear and concise comments
Indentations
....
```

or using Solid Principles
Take Reference from: https://www.topcoder.com/thrive/articles/solid-principles-in-dart

All kinds of contributions in refactoring are valuable to us.

**Comment by Redvey** [comment]
I would like to try

**Comment by droidbg** [comment]
Sure, thanks for offering @Redvey

**Comment by Redvey** [comment]
@droidbg I resolved the warnings and removed the invoked print statements, Is this what we need to do  mostly?

**Comment by droidbg** [comment]
yes thank you, you can raise a PR I will review it. 
It was mostly reducing warnings and using best practices. 
If anything else you want to change from using meaningful variable names to separating common resuable widgets in dls folder you can do so in future PRs.
