### ISSUE TITLE
Altenative of FlutterToast

### ISSUE THREAD

**Issue by droidbg** [droidbg/climator#6]
### Is there an existing issue for this?

- [ ] I have searched the [existing issues](https://github.com/droidbg/climator/issues)
- [ ] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Currently code is using Flutter toast, that are commented in the whole codebase, 
We want to find a alternative that is dart 3 compatible.

### Proposal

Remove this from code and use alternative that is working fine. 

 ```
// Fluttertoast.showToast(
    //     msg: "Fetching WeatherData....",
    //     toastLength: Toast.LENGTH_SHORT,
    //     gravity: ToastGravity.CENTER,
    //     timeInSecForIosWeb: 1);
```

**Comment by MeenuyD** [comment]
Hello @droidbg I would like to work on this issue can you please assign it to me

**Comment by droidbg** [comment]
@MeenuyD no updates on errors in your PR, so assigning this to @ArinNigam
